In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
np.array(l)

array([1, 2, 3, 4])

In [6]:
arr = np.asarray(l)
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [11]:
arr1 = np.array([[1,2,3],[2,3,4]])
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
np.ndim(arr1)

2

In [10]:
np.ndim(arr)

1

In [13]:
mat = np.matrix(l)
mat

matrix([[1, 2, 3, 4]])

In [15]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [16]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [17]:
arr

array([1, 2, 3, 4])

In [18]:
a = arr

In [19]:
arr[0] = 100

In [20]:
arr

array([100,   2,   3,   4])

In [22]:
a   
# this also has changed, we are not creating another memory, a is referening to the same arr in the same location..called as swallow copy

array([100,   2,   3,   4])

In [24]:
b = np.copy(arr)
b

array([100,   2,   3,   4])

In [25]:
b[0] = 234
b

array([234,   2,   3,   4])

In [26]:
arr # this has not changed, so np.copy is creating a seperate memory and b is referencing to this. called as deep copy. 

array([100,   2,   3,   4])

In [27]:
np.fromfunction(lambda i,j : i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [31]:
iterable = (i*i for i in range(5))

In [32]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [34]:
np.fromstring('12 13 14 15', sep =' ')

array([12., 13., 14., 15.])

In [35]:
np.fromstring('12, 13, 14, 15', sep =', ')

array([12., 13., 14., 15.])

In [36]:
arr

array([100,   2,   3,   4])

In [37]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [38]:
arr.ndim

1

In [39]:
arr1.ndim

2

In [40]:
arr.size  # no. of element

4

In [41]:
arr1.size   # total no. of element it is giving

6

In [42]:
arr.shape

(4,)

In [43]:
arr1.shape

(2, 3)

In [44]:
arr.dtype

dtype('int32')

In [45]:
arr1.dtype

dtype('int32')