In [1]:
import numpy as np

In [2]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [4]:
np.arange(.4,10,2)    # it can take floating point as well

array([0.4, 2.4, 4.4, 6.4, 8.4])

In [6]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.zeros((3,4,2))     # 3-d coordinate

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
np.zeros((3,4,2,3))    

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [21]:
arr+3

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [24]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [27]:
arr1 = np.eye(5)   #identity matrix
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
import pandas as pd

In [32]:
df2 = pd.DataFrame(arr1, index = '1 2 3 4 5'.split(), columns = 'a b c d e'.split())
df2

a    b    c    d    e
1  1.0  0.0  0.0  0.0  0.0
2  0.0  1.0  0.0  0.0  0.0
3  0.0  0.0  1.0  0.0  0.0
4  0.0  0.0  0.0  1.0  0.0
5  0.0  0.0  0.0  0.0  1.0

In [33]:
np.random.rand(2,3)

array([[0.43762542, 0.96506692, 0.14432977],
       [0.49486226, 0.57703227, 0.74007006]])

In [34]:
np.random.randn(3,5)    #std normal distribution

array([[ 0.97159214, -1.21887713, -0.0633063 , -0.53123375, -1.44602711],
       [ 0.8535883 ,  0.38959439,  0.00157994, -0.10507084, -0.31665563],
       [-1.03474384,  1.00201891,  0.00743426,  1.08507206,  0.82470081]])

In [37]:
np.random.randint(1,4,(3,4))

array([[3, 1, 3, 1],
       [1, 3, 2, 2],
       [1, 1, 3, 1]])

In [42]:
arr3 = np.random.randint(1,10, (5,6))
arr3

array([[1, 2, 6, 7, 1, 8],
       [2, 4, 6, 9, 1, 6],
       [4, 9, 4, 9, 9, 9],
       [3, 3, 4, 9, 7, 7],
       [6, 6, 1, 2, 2, 1]])

In [43]:
arr3 > 8

array([[False, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False,  True, False,  True,  True,  True],
       [False, False, False,  True, False, False],
       [False, False, False, False, False, False]])

In [44]:
arr3[0,1]

2

In [46]:
arr3[0, [0,1,2]]

array([1, 2, 6])

In [48]:
arr3[2:4, (2,3)]

array([[4, 9],
       [4, 9]])

In [49]:
arr3[2:4, 2:4]

array([[4, 9],
       [4, 9]])

In [51]:
arr3

array([[1, 2, 6, 7, 1, 8],
       [2, 4, 6, 9, 1, 6],
       [4, 9, 4, 9, 9, 9],
       [3, 3, 4, 9, 7, 7],
       [6, 6, 1, 2, 2, 1]])

In [52]:
arr3[1:,2:]

array([[6, 9, 1, 6],
       [4, 9, 9, 9],
       [4, 9, 7, 7],
       [1, 2, 2, 1]])

In [55]:
arr4 = np.random.randint(1,3, (3,3))
arr5 = np.random.randint(1,3, (3,3))

In [56]:
arr4

array([[2, 2, 1],
       [2, 2, 2],
       [2, 1, 1]])

In [57]:
arr5

array([[1, 1, 1],
       [1, 1, 1],
       [1, 2, 1]])

In [58]:
arr4 + arr5

array([[3, 3, 2],
       [3, 3, 3],
       [3, 3, 2]])

In [60]:
arr4 - arr5

array([[ 1,  1,  0],
       [ 1,  1,  1],
       [ 1, -1,  0]])

In [61]:
arr4 * arr5   # this woould be the index multiplication not matrix multiplication

array([[2, 2, 1],
       [2, 2, 2],
       [2, 2, 1]])

In [62]:
arr4 @ arr5    # matrix multiplication

array([[5, 6, 5],
       [6, 8, 6],
       [4, 5, 4]])

In [63]:
arr4/arr5

array([[2. , 2. , 1. ],
       [2. , 2. , 2. ],
       [2. , 0.5, 1. ]])

In [64]:
arr4/0

C:\Users\user\AppData\Local\Temp/ipykernel_41144/1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [65]:
# broadcasting

In [68]:
arr7 = np.zeros((4,5))
arr7

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [69]:
arr7 + 5    # it is called boradcasting in numpy

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [70]:
arr7 + np.array([1,2,3,4,5])

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [71]:
arr7 + np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [88]:
a = np.array([[1,2,3,4]])

In [89]:
arr7 + a.T

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [90]:
a.T

array([[1],
       [2],
       [3],
       [4]])