In [1]:
import pandas as pd


dataset = {
'Name' : ['Sampik','Ayush','Abhay'],
'age' : [20,25,30]
}

pd.DataFrame(dataset)

Name  age
0  Sampik   20
1   Ayush   25
2   Abhay   30

In [2]:
a = [1,2,3]

pd.Series(a, index = ["x","y","z"])

x    1
y    2
z    3
dtype: int64

In [3]:
import numpy as np

In [4]:
np.random.rand(5,5)

array([[0.47163542, 0.58016229, 0.60779747, 0.84623512, 0.65073525],
       [0.69054147, 0.55416101, 0.37518147, 0.48520247, 0.49524087],
       [0.45725635, 0.82829533, 0.33464362, 0.95697006, 0.35913929],
       [0.98342326, 0.70954071, 0.35805141, 0.10027754, 0.86451591],
       [0.43756087, 0.92491268, 0.97302318, 0.36713648, 0.35855875]])

In [7]:
df =pd.DataFrame(np.random.rand(5,5), index = 'a b c d e'.split(), columns = 'abc def ghi jkl mno'.split())
df

abc       def       ghi       jkl       mno
a  0.039549  0.058897  0.777812  0.342917  0.777833
b  0.305343  0.279258  0.783041  0.007772  0.641948
c  0.597115  0.819721  0.335092  0.409056  0.030376
d  0.076892  0.802920  0.437362  0.477870  0.221412
e  0.382478  0.399334  0.653542  0.534011  0.287787

In [8]:
df.drop('abc',axis = 1)   #axis = 1 means, it is representing the column. 

def       ghi       jkl       mno
a  0.058897  0.777812  0.342917  0.777833
b  0.279258  0.783041  0.007772  0.641948
c  0.819721  0.335092  0.409056  0.030376
d  0.802920  0.437362  0.477870  0.221412
e  0.399334  0.653542  0.534011  0.287787

In [10]:
df.drop('c')   # by default, it is taking axis = 0 which is represnting the row

abc       def       ghi       jkl       mno
a  0.039549  0.058897  0.777812  0.342917  0.777833
b  0.305343  0.279258  0.783041  0.007772  0.641948
d  0.076892  0.802920  0.437362  0.477870  0.221412
e  0.382478  0.399334  0.653542  0.534011  0.287787

In [11]:
dictionary = {'abc' : [1,2,3,4,5], 'bef' : [6,7,8,9,10], 'ghi' : [11,12,13,14,15]}

pd.DataFrame(dictionary)

abc  bef  ghi
0    1    6   11
1    2    7   12
2    3    8   13
3    4    9   14
4    5   10   15

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(5,20).reshape(3,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
np.arange(60,5,-1)

array([60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44,
       43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27,
       26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,
        9,  8,  7,  6])

In [19]:
df.shape

(5, 5)

In [21]:
df.dtypes

abc    float64
def    float64
ghi    float64
jkl    float64
mno    float64
dtype: object

In [24]:
df.describe()

abc       def       ghi       jkl       mno
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.280275  0.472026  0.597370  0.354325  0.391871
std    0.229551  0.332980  0.202843  0.206625  0.309060
min    0.039549  0.058897  0.335092  0.007772  0.030376
25%    0.076892  0.279258  0.437362  0.342917  0.221412
50%    0.305343  0.399334  0.653542  0.409056  0.287787
75%    0.382478  0.802920  0.777812  0.477870  0.641948
max    0.597115  0.819721  0.783041  0.534011  0.777833

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   abc     5 non-null      float64
 1   def     5 non-null      float64
 2   ghi     5 non-null      float64
 3   jkl     5 non-null      float64
 4   mno     5 non-null      float64
dtypes: float64(5)
memory usage: 412.0+ bytes
