# Pandas 
***whenever we have to use dataframe and rows or column

In [3]:
import pandas as pd 

In [4]:
labels=['a','b','c','d']

In [5]:
list=[10,28,3,4]

In [6]:
import numpy as np

In [7]:
array=np.array([1,2,3,4])

In [10]:
dict={'w':10,'x':20,'y':30,'z':40}

In [12]:
pd.Series(data=list)

0    10
1    28
2     3
3     4
dtype: int64

In [14]:
pd.Series(data=list,index=labels)

a    10
b    28
c     3
d     4
dtype: int64

In [15]:
pd.Series(labels,list)

10    a
28    b
3     c
4     d
dtype: object

# pandas dataframe and indexing

In [17]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])

In [18]:
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [20]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'])

In [21]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football      15.0
golf           8.0
dtype: float64

In [28]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.584218  0.321758  0.335009  0.234869  0.664683
B  0.630178  0.838517  0.081457  0.226407  0.131934
C  0.545893  0.927480  0.375512  0.632587  0.734600
D  0.276412  0.191296  0.165692  0.548404  0.890795
E  0.473781  0.731212  0.645393  0.173904  0.825305
F  0.868140  0.610624  0.188179  0.821061  0.452391
G  0.945561  0.817869  0.232153  0.954589  0.176728
H  0.338402  0.500875  0.727127  0.064840  0.395610

In [29]:
df1[['Score2','Score1','Score5']]

Score2    Score1    Score5
A  0.321758  0.584218  0.664683
B  0.838517  0.630178  0.131934
C  0.927480  0.545893  0.734600
D  0.191296  0.276412  0.890795
E  0.731212  0.473781  0.825305
F  0.610624  0.868140  0.452391
G  0.817869  0.945561  0.176728
H  0.500875  0.338402  0.395610

In [31]:
df1['Score6']=df1['Score1'] - df1['Score3']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.584218  0.321758  0.335009  0.234869  0.664683  0.249209
B  0.630178  0.838517  0.081457  0.226407  0.131934  0.548722
C  0.545893  0.927480  0.375512  0.632587  0.734600  0.170381
D  0.276412  0.191296  0.165692  0.548404  0.890795  0.110720
E  0.473781  0.731212  0.645393  0.173904  0.825305 -0.171612
F  0.868140  0.610624  0.188179  0.821061  0.452391  0.679960
G  0.945561  0.817869  0.232153  0.954589  0.176728  0.713409
H  0.338402  0.500875  0.727127  0.064840  0.395610 -0.388725

In [32]:
df1.drop('Score5',axis=1)

Score1    Score2    Score3    Score4    Score6
A  0.584218  0.321758  0.335009  0.234869  0.249209
B  0.630178  0.838517  0.081457  0.226407  0.548722
C  0.545893  0.927480  0.375512  0.632587  0.170381
D  0.276412  0.191296  0.165692  0.548404  0.110720
E  0.473781  0.731212  0.645393  0.173904 -0.171612
F  0.868140  0.610624  0.188179  0.821061  0.679960
G  0.945561  0.817869  0.232153  0.954589  0.713409
H  0.338402  0.500875  0.727127  0.064840 -0.388725

In [33]:
df1.drop("E")

Score1    Score2    Score3    Score4    Score5    Score6
A  0.584218  0.321758  0.335009  0.234869  0.664683  0.249209
B  0.630178  0.838517  0.081457  0.226407  0.131934  0.548722
C  0.545893  0.927480  0.375512  0.632587  0.734600  0.170381
D  0.276412  0.191296  0.165692  0.548404  0.890795  0.110720
F  0.868140  0.610624  0.188179  0.821061  0.452391  0.679960
G  0.945561  0.817869  0.232153  0.954589  0.176728  0.713409
H  0.338402  0.500875  0.727127  0.064840  0.395610 -0.388725

In [34]:
df2={'ID': [101,102,103,107,176],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [35]:
###Assessment
#1. create a null vector of size 10.
#2. create a null vector of size 10 but fifth value should be one.
#3. create a vector with values ranging from 10 to 65.
#4. Reverse the above vector.
#5. create a 3*3 matrix with values ranging from 0 to 8.

In [37]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [39]:
z=np.arange(10,66)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

In [42]:
z[:: -1]

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [44]:
z=np.arange(65,9,-1)
z

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [45]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
